name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectKey: Abhijeet2765_simple-java-maven-app
          organization: abhijeet2765
        env:
          SONAR_TOKEN: 974bf7ddff89fe2b90bb1aef95a4c807ee97e0d8
